#!/usr/bin/env python3
"""Generate the NESTED training-set rungs for the I-8 data-scaling curve (T-32).

I-8 asks the one question every WAM negative has so far been excused by and none has tested:
if the same pipeline is given more of the same data, does it get better? That is only a
question about SIZE if size is the only thing that changes between the rungs. Two properties
make that true, and this script exists to produce them as a committed artifact rather than as
a random number generator someone re-runs:

  NESTED   40 ⊂ 120 ⊂ 362, because every rung is a prefix of ONE seeded permutation. A run at
           120 sees everything the 40 run saw plus 80 more episodes, so a difference between
           them cannot be "it drew easier episodes".
  SHUFFLED not a sorted prefix. ``gr00t-apple-000000..40`` is a contiguous block of one
           recording session — take that and rung 40 differs from rung 362 in *when it was
           recorded* as well as in how much there is, and the curve measures both at once.

    python scripts/make_rung_splits.py \
        --dataset datasets/gr00t-apple-full \
        --holdout configs/splits/t18_holdout_episodes.txt \
        --seed 0 --rungs 40,120,362 --out configs/splits

Output is deterministic: same dataset, same holdout, same seed -> byte-identical files, header
included (no timestamps, paths normalised to repo-relative). ``tests/test_splits.py`` pins that,
so the committed files and the code that produced them cannot drift apart.
"""

from __future__ import annotations

import argparse
import hashlib
import random
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))

DEFAULT_PREFIX = "i8_train_"


def _repo_relative(path: Path) -> str:
    """``path`` as seen from the repo root when it lives inside it, else unchanged.

    The header is part of the file's bytes and the file is committed, so an absolute path would
    make the artifact depend on whose laptop generated it — and the determinism test would fail
    for a reason that has nothing to do with the split.
    """
    resolved = Path(path).resolve()
    try:
        return str(resolved.relative_to(_REPO_ROOT))
    except ValueError:
        return str(path)


def _sha256(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def rung_ids(pool: list[str], size: int, seed: int) -> list[str]:
    """The ``size`` episode ids of the rung, sorted for readability but chosen by ``seed``.

    ``pool`` must already be in a canonical order (``list_episodes`` is sorted); the shuffle is
    what makes the choice arbitrary with respect to recording order, and taking a PREFIX of the
    one permutation is what makes the rungs nested.
    """
    if size > len(pool):
        raise SystemExit(f"rung {size} exceeds the {len(pool)} available training episodes")
    order = list(pool)
    random.Random(seed).shuffle(order)
    return sorted(order[:size])


def render(
    ids: list[str], *, size: int, seed: int, dataset: Path, holdout: Path, pool_size: int
) -> str:
    """The file body: a self-documenting header (the shape t18_holdout_episodes.txt uses) + ids."""
    return "".join(
        f"{line}\n"
        for line in (
            f"# I-8 / T-32 data-scaling rung — {size} training episodes.",
            "# Pass to train_t16_lora.py --train-episodes together with the SAME",
            "# --exclude-episodes holdout this file was generated against.",
            "#",
            "# Generated by:",
            f"#   python scripts/make_rung_splits.py --dataset {_repo_relative(dataset)} \\",
            f"#       --holdout {_repo_relative(holdout)} --seed {seed} --rungs {size} \\",
            "#       --out configs/splits",
            "#",
            f"# seed:          {seed} (one permutation; every rung is a PREFIX of it, so the",
            "#                rungs are nested and size is the only thing that varies)",
            f"# dataset:       {_repo_relative(dataset)}",
            f"# holdout:       {_repo_relative(holdout)}",
            f"#                sha256:{_sha256(holdout)}",
            f"# training pool: {pool_size} episodes (dataset minus holdout)",
            f"# this rung:     {size} episodes",
            *ids,
        )
    )


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dataset", type=Path, default=_REPO_ROOT / "datasets" / "gr00t-apple-full"
    )
    parser.add_argument(
        "--holdout",
        type=Path,
        default=_REPO_ROOT / "configs" / "splits" / "t18_holdout_episodes.txt",
        help="the episodes the rungs must never contain (default: the T-18 holdout)",
    )
    parser.add_argument(
        "--seed", type=int, default=0, help="permutation seed (default: %(default)s)"
    )
    parser.add_argument("--rungs", type=str, default="40,120,362", help="comma-separated sizes")
    parser.add_argument("--out", type=Path, default=_REPO_ROOT / "configs" / "splits")
    parser.add_argument("--prefix", type=str, default=DEFAULT_PREFIX, help="output filename prefix")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    from wam.data.episode import list_episodes
    from wam.evaluation import load_episode_ids

    episodes = list_episodes(args.dataset)
    if not episodes:
        raise SystemExit(f"no episodes under {args.dataset}")
    holdout = load_episode_ids(args.holdout)
    present = {p.name for p in episodes}
    absent = sorted(holdout - present)
    if absent:
        # A holdout that does not line up with the dataset means the rungs would be generated
        # against a different split than the evaluator will later prove — fatal, not a warning.
        raise SystemExit(
            f"--holdout lists {len(absent)} episode(s) absent from {args.dataset}: {absent[:5]}"
        )
    pool = [p.name for p in episodes if p.name not in holdout]

    args.out.mkdir(parents=True, exist_ok=True)
    for size in (int(s) for s in args.rungs.split(",") if s.strip()):
        ids = rung_ids(pool, size, args.seed)
        path = args.out / f"{args.prefix}{size:03d}.txt"
        path.write_text(
            render(
                ids,
                size=size,
                seed=args.seed,
                dataset=args.dataset,
                holdout=args.holdout,
                pool_size=len(pool),
            )
        )
        print(f"{path}: {len(ids)} episodes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
